name: good workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyDotNetApp/MyDotNetApp.csproj

    - name: Build
      run: dotnet build MyDotNetApp/MyDotNetApp.csproj --no-restore

    - name: Test
      run: dotnet test MyDotNetApp/MyDotNetApp.csproj --no-build

    - name: Run Additional Scripts
      run: ./run-scripts.sh
      if: success()

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Deploy to Production
      run: echo "Deploying to Production"
